version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - microservices-net

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      EUREKA_URL: http://eureka-server:8761
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  resource-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: resource-db
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_PORT}:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RESOURCE_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

  song-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: song-db
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_PORT}:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SONG_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

  storage-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: storage-db
    environment:
      POSTGRES_DB: ${STORAGE_DB}
      POSTGRES_USER: ${STORAGE_DB_USER}
      POSTGRES_PASSWORD: ${STORAGE_DB_PASSWORD}
    ports:
      - "${STORAGE_DB_PORT}:5432"
    volumes:
      - ./init-scripts/storage-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${STORAGE_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    container_name: resource-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: "${RESOURCE_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${RESOURCE_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${RESOURCE_DB_PASSWORD}"
      SONG_SERVICE_NAME: "song-service"
      SONG_SERVICE_PORT: "8082"
      STORAGE_SERVICE_NAME: "storage-service"
      STORAGE_SERVICE_PORT: "8086"
      EUREKA_URL: http://eureka-server:8761
      KAFKA_URL: "kafka:9092"
    depends_on:
      resource-db:
        condition: service_healthy
      resource-processor:
        condition: service_started
      song-service:
        condition: service_started
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  resource-processor:
    build:
      context: ./resource-processor
      dockerfile: Dockerfile
    container_name: resource-processor
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      RESOURCE_SERVICE_NAME: "resource-service"
      RESOURCE_SERVICE_PORT: "8081"
      SONG_SERVICE_NAME: "song-service"
      SONG_SERVICE_PORT: "8082"
      EUREKA_URL: http://eureka-server:8761
      KAFKA_URL: "kafka:9092"
    depends_on:
      song-service:
        condition: service_started
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    container_name: song-service
    deploy:
      replicas: 1
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: "${SONG_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${SONG_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${SONG_DB_PASSWORD}"
      EUREKA_URL: http://eureka-server:8761
    depends_on:
      song-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    container_name: storage-service
    deploy:
      replicas: 1
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      SPRING_DATASOURCE_URL: "${STORAGE_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${STORAGE_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${STORAGE_DB_PASSWORD}"
      EUREKA_URL: http://eureka-server:8761
    depends_on:
      storage-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
