spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=song-service
spring.cloud.gateway.routes[0].uri=lb://song-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/songs/**

spring.cloud.gateway.routes[1].id=resource-service
spring.cloud.gateway.routes[1].uri=lb://resource-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/resources/**

spring.cloud.gateway.routes[2].id=resource-processor
spring.cloud.gateway.routes[2].uri=lb://resource-processor
spring.cloud.gateway.routes[2].predicates[0]=Path=/metadata/**

server.port=8080

eureka.client.serviceUrl.defaultZone=http://${EUREKA_URI:localhost}:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


