spring.application.name=storage-service
server.port=${SERVER_PORT:8086}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/storage_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
#spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761}/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.service-registry.auto-registration.enabled=true
eureka.client.enabled=true
eureka.client.register-with-eureka=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# JVM Metrics
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

# Custom Application Metrics
management.metrics.enable.http=true
management.metrics.enable.kafka=true

logging.level.com.learn=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN